# =============================================================================
# Project: [Project Name]
# Author:  [Author]
# Date:    [Date]
# =============================================================================


# -----------------------------------------------------------------------------
# 1. Description
# -----------------------------------------------------------------------------
# [Describe the purpose and goals of this project here.]
#
# Key objectives:
#   - [Objective 1]
#   - [Objective 2]
#   - [Objective 3]


# -----------------------------------------------------------------------------
# 2. renv Environment
# -----------------------------------------------------------------------------
# This project uses renv to manage package dependencies. The renv.lock file
# records the exact package versions used, ensuring reproducibility.
#
# To add a new package to the project:
#   renv::install("package_name")
#   renv::snapshot()
#
# To restore the environment on a different computer (after pulling from Git):
#   renv::restore()
#
# To check the status of your renv environment:
#   renv::status()


# -----------------------------------------------------------------------------
# 3. Functions
# -----------------------------------------------------------------------------
# Source all functions from the /R directory. Each function file should contain
# one primary function with roxygen2 documentation tags.

r_files <- list.files("R", pattern = "\\.R$", full.names = TRUE)
invisible(lapply(r_files, source))


# -----------------------------------------------------------------------------
# 4. Data Loading
# -----------------------------------------------------------------------------
# This section loads any source data required for analysis. Place raw data
# files in the /data directory.

# Example:
# df <- readr::read_csv("data/source_data.csv")


# -----------------------------------------------------------------------------
# 5. Main Code
# -----------------------------------------------------------------------------
# This is the main analysis section. Write the primary analytic code here,
# calling functions sourced from the /R directory as needed.


# -----------------------------------------------------------------------------
# 6. Output
# -----------------------------------------------------------------------------
# Save any output data, tables, figures, or reports generated by the analysis.

# Example:
# readr::write_csv(results, "data/output_results.csv")
# ggsave("output/figure1.png", plot = fig1, width = 10, height = 6)
